[{* D3 ArticleVoucher *}]
[{d3modcfgcheck modid="d3articlevoucher"}][{/d3modcfgcheck}]
[{if $mod_d3articlevoucher}]
    [{if $oViewConf->getShowVouchers()}]
        [{if $oModCfg_d3articlevoucher->isThemeIdMappedTo('wave')}]
            [{include file='@d3articlevoucher/wave/checkout_basketcontents_voucherdiscount.tpl'}]
        [{else}]
        [{/if}]
    [{/if}]
[{* D3 ArticleVoucher *}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]
