[{d3modcfgcheck modid="d3articlevoucher"}]
[{/d3modcfgcheck}]
[{if $mod_d3articlevoucher}]
    [{if $oModCfg_d3articlevoucher->isThemeIdMappedTo('flow')}]
        [{if $basketitem->getdBundledAmount() > 0 && ($basketitem->isBundle() || $basketitem->isDiscountArticle())}]
            [{include file='checkout_basketcontents_basketitem_removecheckbox_table_flow.tpl'}]
        [{else}]
            [{$smarty.block.parent}]
        [{/if}]
    [{else}]
        [{$smarty.block.parent}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]