[{* D3 ArticleVoucher *}]
[{d3modcfgcheck modid="d3articlevoucher"}][{/d3modcfgcheck}]
[{if $mod_d3articlevoucher}]
    [{if $oViewConf->getShowVouchers()}]
        [{if $oModCfg_d3articlevoucher->isThemeIdMappedTo('azure')}]
            [{include file='checkout_basketcontents_voucherdiscount_azure.tpl'}]
        [{elseif $oModCfg_d3articlevoucher->isThemeIdMappedTo('flow')}]
            [{include file='checkout_basketcontents_voucherdiscount_flow.tpl'}]
        [{elseif $oModCfg_d3articlevoucher->isThemeIdMappedTo('wave')}]
            [{include file='checkout_basketcontents_voucherdiscount_wave.tpl'}]
        [{else}]
        [{/if}]
    [{/if}]
[{* D3 ArticleVoucher *}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]
